import { Button, VerticalBox } from "std-widgets.slint";
import { Palette } from "../components/palette.slint";
import { customButton } from "../components/customButton.slint";
import { keypad_button } from "../components/keypad_button.slint";
export component accept inherits Rectangle {
    in property <string> amount: "";
    in property <image> current_frame;
    
    VerticalBox {
        spacing: 24px;

        Image {
            source: current_frame;
            width: 150px;
            height: 150px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        Text {
            color: Palette.textColorMain;
            text: "Payment Accepted!";
            font-family: Palette.fontFamily;
            font-size: 64px;
            font-weight: 700;
        }

        Text {
            color: Palette.textColorAccent;
            text: "Your new balance is £"+ amount;
            font-family: Palette.fontFamily;
            font-size: 32px;
            font-weight: 400;
        }
    }

    Rectangle {
        width: 100%;
        height: 100%;

        // Top Right

        customButton {
            text: Palette.highContrast ? "Disable High Contrast" : "Enable High Contrast";
            custom_width: 400;
            custom_height: 150;
            x: parent.width - 420px;
            y: 16px;
            custom_font_size: 30;
            custom_font_weight: 700;
            callback => {
                Palette.highContrast = !Palette.highContrast
            };
        }

        // Bottom

        Text {
            text: "Vapour Payment Terminal";
            font-size: 15px;
            font-family: Palette.fontFamily;
            font-weight: 300;
            color: Palette.textColorAccent;
            x: 16px;
            y: parent.height - self.height - 16px;
        }

        Text {
            text: "Made with ❤️ by iSophes";
            font-size: 15px;
            font-family: Palette.fontFamily;
            font-weight: 300;
            color: Palette.textColorAccent;
            x: parent.width - self.width - 16px;
            y: parent.height - self.height - 16px;
        }
    }
}
