import { Button, VerticalBox } from "std-widgets.slint";
import { Palette } from "../components/palette.slint";
import { customButton } from "../components/customButton.slint";
import { keypad_button } from "../components/keypad_button.slint";
export component accept inherits Rectangle {
    in property <string> amount: "";

    VerticalLayout {
        alignment: center;
        spacing: 24px;

        Image {
            source: @image-url("../assets/check.png");
            width: 150px;
            height: 150px;
            vertical-alignment: center;
            horizontal-alignment: center;
            x: (parent.width / 2) - (self.width / 2);
        }

        Text {
            color: Palette.textColorMain;
            text: "Payment Accepted!";
            font-family: Palette.fontFamily;
            font-size: 64px;
            font-weight: 700;
            x: (parent.width / 2) - (self.width / 2);
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        Text {
            color: Palette.textColorAccent;
            text: "Your new balance is " + amount;
            font-family: Palette.fontFamily;
            font-size: 32px;
            font-weight: 400;
            x: (parent.width / 2) - (self.width / 2);
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }

    Rectangle {
        width: 100%;
        height: 100%;

        // Bottom

        Text {
            text: "Vapour Payment Terminal";
            font-size: 15px;
            font-family: Palette.fontFamily;
            font-weight: 300;
            color: Palette.textColorAccent;
            x: 16px;
            y: parent.height - self.height - 16px;
        }

        Text {
            text: "Made with ❤️ by iSophes";
            font-size: 15px;
            font-family: Palette.fontFamily;
            font-weight: 300;
            color: Palette.textColorAccent;
            x: parent.width - self.width - 16px;
            y: parent.height - self.height - 16px;
        }
    }
}
