import { Button, VerticalBox } from "std-widgets.slint";
import { Palette } from "../components/palette.slint";
import { customButton } from "../components/customButton.slint";

export component fail inherits Rectangle {
    in property <string> amount: "";
    callback cancel();
    callback retry();

    VerticalLayout {
        alignment: center;
        spacing: 32px;

        Image {
            source: @image-url("../assets/decline.png");
            width: 150px;
            height: 150px;
            vertical-alignment: center;
            horizontal-alignment: center;
            x: (parent.width / 2) - (self.width / 2);
        }

        Text {
            color: Palette.textColorMain;
            text: "Oh no! Something went wrong on our end.";
            font-family: Palette.fontFamily;
            font-size: 64px;
            font-weight: 700;
            x: (parent.width / 2) - (self.width / 2);
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        Text {
            color: Palette.textColorAccent;
            text: "No money has been taken from your account. Try again later.";
            font-family: Palette.fontFamily;
            font-size: 48px;
            font-weight: 700;
            x: (parent.width / 2) - (self.width / 2);
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        customButton {
            custom_width: 400;
            custom_height: 100;
            text: "Retry";
            callback => {
                retry()
            };
            custom_font_size: 32;
            custom_font_weight: 400;
            x: (parent.width / 2) - (self.width / 2);
        }

        customButton {
            custom_width: 400;
            custom_height: 100;
            text: "Cancel";
            callback => {
                cancel()
            };
            custom_font_size: 32;
            custom_font_weight: 400;
            x: (parent.width / 2) - (self.width / 2);
        }
    }

    Rectangle {
        width: 100%;
        height: 100%;

        // Bottom

        Text {
            text: "Vapour Payment Terminal";
            font-size: 15px;
            font-family: Palette.fontFamily;
            font-weight: 300;
            color: Palette.textColorAccent;
            x: 16px;
            y: parent.height - self.height - 16px;
        }

        Text {
            text: "Made with ❤️ by iSophes";
            font-size: 15px;
            font-family: Palette.fontFamily;
            font-weight: 300;
            color: Palette.textColorAccent;
            x: parent.width - self.width - 16px;
            y: parent.height - self.height - 16px;
        }
    }
}
