import { LineEdit } from "std-widgets.slint";
import { Palette } from "../components/palette.slint";
import { customButton } from "../components/customButton.slint";
export component PasswordInput inherits Rectangle {
    property <bool> showPassword: false;
    out property <string> inputted_password;
    callback submit_password(string);
    callback go_back();

    VerticalLayout {
        alignment: center;
        spacing: 20px;
        
        Text {
            x: (parent.width / 2) - (self.width / 2);
            horizontal-alignment: center;
            width: 50%;
            height: 10%;
            text: "Please enter your MY RUNSHAW Password. (The unofficial student app)";
            font-weight: 600;
            font-family: Palette.fontFamily;
            font-size: 30px;
            color: Palette.textColorMain;
        }

        Rectangle {
            x: (parent.width / 2) - (self.width / 2);
            border-radius: 4px;
            border-color: Palette.highContrast ? #ffff00 : #45475a;
            border-width: 2px;
            width: 300px;
            height: 100px;
            background: Palette.highContrast ? #000000 : #313244;

            LineEdit {

                placeholder-text: "Password";
                input-type: showPassword ? text : password; 
                font-size: 20px;
                font-family: Palette.fontFamily;
                edited(text) => {inputted_password = text;}
            }
        }

        customButton {
            x: (parent.width / 2) - (self.width / 2);
            text: "Submit";
            custom_width: 300;
            custom_height: 100;
            custom_font_size: 20;
            custom_font_weight: 600;
            callback => {submit_password(inputted_password)}
        }

        customButton {
            x: (parent.width / 2) - (self.width / 2);
            text: "Exit";
            custom_width: 200;
            custom_height: 100;
            custom_font_size: 20;
            custom_font_weight: 600;
            callback => {go_back()}
        }
    }
}