import { Button, StyleMetrics } from "std-widgets.slint";
import { Palette } from "palette.slint";
export component customButton inherits TouchArea {
    in property <string> text;
    in property <int> custom_width;
    in property <int> custom_height;
    in property <int> custom_font_size;
    in property <int> custom_font_weight;

    callback callback;

    width: custom_width * 1px;
    height: custom_height * 1px;

    clicked => root.callback();

    Rectangle {
        border-radius: 4px;
        border-color: Palette.highContrast ? #ffff00 : #45475a;
        border-width: 2px;
        width: custom_width * 1px;
        height: custom_height * 1px;
        background: Palette.highContrast ? #000000 : #313244;

        animate border-color { duration: 300ms; }

        animate background { duration: 300ms; }

        Text {
            font-size: custom_font_size * 1px;
            font-weight: custom_font_weight;
            text: root.text;
            font-family: Palette.fontFamily;
            horizontal-alignment: center;
            vertical-alignment: center;
            color: Palette.highContrast ? #ffffff : #a6adc8;
            animate color { duration: 300ms; }
        }
    }
}
